VECTORZERO = HL2.Vector(0, 0, 0);


NODETYPE = {
	NODE_ANY = 0, 
	NODE_DELETED= 1,
	NODE_GROUND= 2,
	NODE_AIR= 3,
	NODE_CLIMB= 4,
	NODE_WATER= 5,
	};

MOVETYPE = {
	MOVETYPE_NONE = 0, 
	MOVETYPE_WALK = 2,
	MOVETYPE_STEP = 3,
	MOVETYPE_FLY= 4,
	MOVETYPE_FLYGRAVITY = 5,
	MOVETYPE_VPHYSICS = 6,
	MOVETYPE_NOCLIP = 8,
	};

DISPOSITION = {
	D_HT = 1,
	D_FR = 2,
	D_LI = 3,
	D_NU = 4,
};

CLASS = {
	CLASS_NONE =0,
	CLASS_PLAYER = 1,
	CLASS_PLAYER_ALLY = 2,
	CLASS_PLAYER_ALLY_VITAL = 3,
	CLASS_ANTLION = 4,
	CLASS_BARNACLE = 5,
	CLASS_BULLSEYE = 6,
	CLASS_CITIZEN_PASSIVE = 7,	
	CLASS_CITIZEN_REBEL = 8,
	CLASS_COMBINE=9,
	CLASS_COMBINE_GUNSHIP=10,
	CLASS_HEADCRAB=12,
	CLASS_MANHACK=13,
	CLASS_METROPOLICE=14,
	CLASS_MILITARY=15,
	CLASS_SCANNER=16,
	CLASS_STALKER=17,
	CLASS_VORTIGAUNT=18,
	CLASS_ZOMBIE=19,
	CLASS_PROTOSNIPER=20,
	CLASS_MISSILE=21,
	CLASS_FLARE=22,
	CLASS_EARTH_FAUNA=23
}

print("*** load constant values. \n")

